"""add interview metadata to conversations

Revision ID: f3bcf1f5e34a
Revises: 0f160c703113
Create Date: 2026-05-24 19:55:42.681254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3bcf1f5e34a'
down_revision: Union[str, None] = '0f160c703113'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'conversations',
        sa.Column(
            'job_position',
            sa.String(length=255),
            nullable=False,
            server_default='dev'
        )
    )

    op.add_column(
        'conversations',
        sa.Column(
            'company_name',
            sa.String(length=255),
            nullable=True
        )
    )

    # Xóa default tạm sau khi fill dữ liệu cũ
    op.alter_column(
        'conversations',
        'job_position',
        server_default=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'company_name')
    op.drop_column('conversations', 'job_position')
    # ### end Alembic commands ###
