"""add column embedding url

Revision ID: b23551a6ec8d
Revises: 1bef7696bbf2
Create Date: 2026-06-09 21:51:06.871583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b23551a6ec8d'
down_revision: Union[str, None] = '20260604100000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_sessions', sa.Column('career_objectives_score', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('cv_profiles', sa.Column('embedding_vector_url', sa.String(length=500), nullable=True))
    op.add_column('job_descriptions', sa.Column('embedding_vector_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_descriptions', 'embedding_vector_url')
    op.drop_column('cv_profiles', 'embedding_vector_url')
    op.drop_column('analysis_sessions', 'career_objectives_score')
    # ### end Alembic commands ###
