"""add_cv_score_overrides

Revision ID: 1bef7696bbf2
Revises: 20260518080000
Create Date: 2026-05-30 16:01:50.152605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1bef7696bbf2'
down_revision: Union[str, None] = '20260518080000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cv_score_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cv_id', sa.String(), nullable=False),
    sa.Column('jd_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('overridden_scores', sa.JSON(), nullable=False),
    sa.Column('rationale', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cv_score_overrides_cv_id'), 'cv_score_overrides', ['cv_id'], unique=False)
    op.create_index(op.f('ix_cv_score_overrides_id'), 'cv_score_overrides', ['id'], unique=False)
    op.create_index(op.f('ix_cv_score_overrides_jd_id'), 'cv_score_overrides', ['jd_id'], unique=False)
    op.create_index(op.f('ix_cv_score_overrides_user_id'), 'cv_score_overrides', ['user_id'], unique=False)
    op.drop_index('ix_conversation_analysis_reports_conversation_id', table_name='conversation_analysis_reports')
    op.drop_index('ix_conversation_analysis_reports_id', table_name='conversation_analysis_reports')
    op.drop_table('conversation_analysis_reports')
    op.drop_column('conversations', 'started_at')
    op.drop_column('conversations', 'ended_at')
    op.drop_column('conversations', 'company_name')
    op.drop_column('conversations', 'interview_duration_seconds')
    op.drop_column('conversations', 'job_position')
    op.drop_constraint('permissions_code_key', 'permissions', type_='unique')
    op.drop_index('ix_permissions_code', table_name='permissions')
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.drop_constraint('roles_name_key', 'roles', type_='unique')
    op.drop_index('ix_roles_name', table_name='roles')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_index('ix_roles_name', 'roles', ['name'], unique=False)
    op.create_unique_constraint('roles_name_key', 'roles', ['name'])
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.create_index('ix_permissions_code', 'permissions', ['code'], unique=False)
    op.create_unique_constraint('permissions_code_key', 'permissions', ['code'])
    op.add_column('conversations', sa.Column('job_position', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('conversations', sa.Column('interview_duration_seconds', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('conversations', sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('conversations', sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('conversations', sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.create_table('conversation_analysis_reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('overall_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('overall_grade', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('level', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('scores', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('ai_coach_insights', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('strengths', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('weaknesses', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('knowledge_gaps', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('study_plan', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('raw_ai_response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name='conversation_analysis_reports_conversation_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='conversation_analysis_reports_pkey'),
    sa.UniqueConstraint('conversation_id', name='uq_conversation_analysis_reports_conversation_id')
    )
    op.create_index('ix_conversation_analysis_reports_id', 'conversation_analysis_reports', ['id'], unique=False)
    op.create_index('ix_conversation_analysis_reports_conversation_id', 'conversation_analysis_reports', ['conversation_id'], unique=False)
    op.drop_index(op.f('ix_cv_score_overrides_user_id'), table_name='cv_score_overrides')
    op.drop_index(op.f('ix_cv_score_overrides_jd_id'), table_name='cv_score_overrides')
    op.drop_index(op.f('ix_cv_score_overrides_id'), table_name='cv_score_overrides')
    op.drop_index(op.f('ix_cv_score_overrides_cv_id'), table_name='cv_score_overrides')
    op.drop_table('cv_score_overrides')
    # ### end Alembic commands ###
