"""add_ci_raw_text_to_analysis_sessions

Revision ID: 0f160c703113
Revises: 37ad13d06aab
Create Date: 2026-05-21 00:42:05.316517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f160c703113'
down_revision: Union[str, None] = '37ad13d06aab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_sessions', sa.Column('cv_raw_text', sa.Text(), nullable=True))
    op.add_column('analysis_sessions', sa.Column('jd_raw_text', sa.Text(), nullable=True))
    op.add_column('analysis_sessions', sa.Column('ci_raw_text', sa.Text(), nullable=True))
    op.add_column('company_infos', sa.Column('text_content', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_infos', 'text_content')
    op.drop_column('analysis_sessions', 'ci_raw_text')
    op.drop_column('analysis_sessions', 'jd_raw_text')
    op.drop_column('analysis_sessions', 'cv_raw_text')
    # ### end Alembic commands ###
